name: Sync Website Folder

on:
  push:
    paths:
      - 'website/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v3

      - name: Clone Public Repo
        run: |
          git clone https://github.com/vineelvanjari/website-content.git public

      - name: Sync Entire Website Folder
        run: |
          rsync -av --delete website/ public/

      - name: Commit and Push Changes
        run: |
          cd public
          git config user.name "vineelvanjari"
          git config user.email "your-email@example.com"
          git add .
          git commit -m "Auto-sync full website folder" || echo "No changes"
          git push https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/vineelvanjari/website-content.git HEAD:main